<a href="https://colab.research.google.com/github/krmonline/AnomalyDetection/blob/master/Autoencoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import  tensorflow as tf
import numpy as np
from sklearn.metrics import mean_squared_error 

In [15]:
x = [0,1,2,3,4,5,6,7]
X = tf.keras.utils.to_categorical(x)
X

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [16]:
inputs = tf.keras.Input(shape=X.shape[1])
encoder = tf.keras.layers.Dense(3, activation='sigmoid')
decoder = tf.keras.layers.Dense(X.shape[1], activation='sigmoid')
outputs = decoder(encoder(inputs))
model = tf.keras.Model(inputs,outputs)

In [17]:
model.compile(loss=tf.keras.losses.MeanSquaredError(),
              optimizer=tf.keras.optimizers.SGD(learning_rate=3.5))

In [70]:
model.fit(X,X,epochs=2000,verbose=0)

In [71]:
pred = model.predict(np.array([[0., 1., 0., 0., 0., 0., 0., 0.]]))
print(pred)
print(np.round(pred))

[[1.0024011e-03 8.8290018e-01 9.2455745e-04 8.0137193e-02 2.5001941e-06
  7.5644404e-02 5.0887555e-02 5.4100972e-05]]
[[0. 1. 0. 0. 0. 0. 0. 0.]]


In [72]:
z = np.round(model(X))

In [73]:
z

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [74]:
encoder(X)

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[0.9524715 , 0.9635762 , 0.01263168],
       [0.01338285, 0.98836184, 0.7966691 ],
       [0.12841552, 0.01613548, 0.11676043],
       [0.9819336 , 0.97270596, 0.9803817 ],
       [0.9748137 , 0.08331805, 0.11791453],
       [0.01990184, 0.23579267, 0.9585848 ],
       [0.04617923, 0.7569177 , 0.01393664],
       [0.81826794, 0.01202166, 0.973783  ]], dtype=float32)>

In [75]:
np.round(encoder(X))

array([[1., 1., 0.],
       [0., 1., 1.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.]], dtype=float32)

In [78]:
x_test = np.array([[0,0,0]])
result =  decoder(x_test)
print(result)
print(np.round(result))

tf.Tensor(
[[2.28142738e-03 1.06957555e-03 9.47694898e-01 7.18324736e-05
  6.73275590e-02 1.11555606e-01 3.86252165e-01 5.02637029e-03]], shape=(1, 8), dtype=float32)
[[0. 0. 1. 0. 0. 0. 0. 0.]]
